// Lista canônica de secretarias/CC. Mantém os nomes sempre iguais entre meses
// para o gráfico e o ranking não "duplicarem" a mesma secretaria por causa de
// acento ou grafia diferente vinda do PDF. Se uma secretaria nova aparecer,
// adicione o nome exato aqui.
export const CANONICAL_SECRETARIAS = [
  'SECRETARIA DE ADMINISTRACAO',
  'S.M.T.T',
  'SECRETARIA DE ASSISTENCIA SOCIAL',
  'SECRETARIA DE SAUDE',
  'SECRETARIA DE INFRAESTRUTURA',
  'SECRETARIA DE EDUCACAO',
  'PENSIONISTA/APOSENTADOS',
  'SECRETARIA DA INFANCIA E DA JUVENTUDE',
  'SEC.MUNICIPAL DE SEGURANCA URBANA',
  'SECRETARIA DE ESPORTE E LAZER',
  'SEC. DE COMUNICACAO SOCIAL MARKT EVENTOS',
  'SECRETARIA DA MULHER',
  'SECRETARIA DE ARTICULACAO POLITICA',
  'SECRETARIA DE GABINETE CIVIL',
  'SECRETARIA DE FINANCAS',
  'SECRETARIA DE CULTURA',
  'SECRETARIA MUNICIPAL DE DESENVOLVIMENTO ECONÔMICO',
  'PROCURADORIA GERAL',
  'CONTROLADORIA GERAL',
  'SECRETARIA DE MEIO AMBIENTE',
  'SECRETARIA DE AGRICULTURA',
  'SECRETARIA DE PLANEJAMENTO E GOVERNANCA',
  'FUNDEB 70%',
  'PROCESSO SELETIVO 70%',
  'FUNDEB 30% EFETIVO',
  'FUNDEB 30% CONTRATO',
];

export const ENTIDADES = ['PREFEITURA', 'DINAMICA', 'COOPREV'];

export const ENTIDADE_LABELS = {
  PREFEITURA: 'Prefeitura',
  DINAMICA: 'Dinâmica',
  COOPREV: 'Saudemed',
  TODAS: 'Consolidado',
};

export const MESES = [
  'JANEIRO', 'FEVEREIRO', 'MARÇO', 'ABRIL', 'MAIO', 'JUNHO',
  'JULHO', 'AGOSTO', 'SETEMBRO', 'OUTUBRO', 'NOVEMBRO', 'DEZEMBRO',
];

export const MESES_ABREV = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'];
